### ISSUE TITLE
Compiler API should avoid use of public fields

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#1035]
In C#, it's best practice to use properties instead of fields when the field is public. Properties are more flexible than fields because they allow changing their internal implementation, and fields cannot implement any interface member, while properties can. Changing a field to a property is a breaking binary change, however.

Since we are concerned with binary compatibility as part of the rewrite step API, where we want to be able to continue loading assemblies compiled for older Q# compiler versions for as long as possible, we should consider forbidding the use of public fields. We can enable the SA1401 StyleCop rule (which is enabled by default, but is currently disabled in editorconfig) to enforce this.

**Comment by bettinaheim** [comment]
Just capturing what we discussed: 
Overall, it seems less invasive to replace public fields by the corresponding properties rather than deprecating public fields and introduce new properties. That will mean a breaking change for all compiler extensions (old extensions work with old compilers but new compiler versions will not be able to load extension until they change the referenced compiler version), and similarly for version conflicts when a project depends indirectly on multiple compiler versions. However, as far as using the API is concerned, there shouldn't be any change. I am good with moving forward with this, and happy to hear about any concerns if there are any.

**Comment by filipw** [comment]
I think this is a very good idea and I don't think it would be too invasive to just change them into properties. 

On a somewhat related note, I also think that constructors should be free of side effects - e.g. It is a bit awkward that compilation happens in the constructor of `CompilationLoader` (not to mention constructors cannot be async).

**Comment by samarsha** [comment]
> On a somewhat related note, I also think that constructors should be free of side effects - e.g. It is a bit awkward that compilation happens in the constructor of `CompilationLoader` (not to mention constructors cannot be async).

Seems reasonable, do you want to make a separate issue for that, @filipw?
