### ISSUE TITLE
Code actions not working in latest version of VS

### ISSUE THREAD

**Issue by guenp** [microsoft/qsharp-compiler#1067]
**Describe the bug**

"Code actions" do not work in current VS extension on latest version of Visual studio (
**To Reproduce**

1. Install the latest version of Visual Studio (16.10.2)
2. Download and install the QDK extension
3. Try editing a file and introduce typo's and deprecated syntax that would trigger a code action

**Expected behavior**

I would expect green squiggly lines to show up on lines with available code actions.

**Screenshots**

Expected behavior:

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/4041805/123490398-ca59f280-d5c8-11eb-84a3-bc8c82f931d2.png)

Actual behavior:

![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/4041805/123490409-cfb73d00-d5c8-11eb-82f0-c0cb2f2c4f18.png)

**System information**

- QDK version v0.18.2106.148911
- Windows 10
- Visual studio 16.10.2

**Additional context**

The extension is working on older versions of Visual Studio. The latest release 10.16 was introduced in May: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes

**Comment by ricardo-espinoza** [comment]
Code Actions are broken in Visual Studio 16.10 and above because of a more strict implementation of the Language Server Protocol. 

Per the LSP specification, `textNotification/didChange` events include a document version number that changes every time the document is updated in the editor. When applying a CodeAction, it is expected that the field `documentChanges/textDocument/version` in the workspace edit corresponds to the current version of the affected document. 

Formerly, this version match was not enforced, so a default value of 1 was used. This however is no longer permitted in 16.10 and above.

This is addressed by pull request #1085 .

**Comment by ricardo-espinoza** [comment]
Fixed in #1085 , targeting the next QDK version.
