### ISSUE TITLE
How to run the QsCompiler regression testcases?

### ISSUE THREAD

**Issue by QuXing9** [microsoft/qsharp-compiler#1111]
Hello, I found that the QSharp compiler provides some regression test cases [here](https://github.com/microsoft/qsharp-compiler/tree/main/src/QsCompiler/Tests.Compiler). It seems an F# project. I opened the [F# project](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsCompiler/Tests.Compiler/Tests.Compiler.fsproj) using the vs2019. When I run a qsharp file for example [Arithmetic_input.qs](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsCompiler/Tests.Compiler/TestCases/OptimizerTests/Arithmetic_input.qs) in the F# project, vs2019 reports some errors such as `FS0039  The namespace 'TextProcessing' is not defined`、`FS0039  The namespace or module 'SyntaxTree' is not defined`.

I am a beginner of the F#, I want to ask that where I can find these namespaces to execute test cases normally? 
Looking forward to your reply, Thank you very much~

**Comment by bettinaheim** [comment]
@QuXing9 Did you try to run the test either from within the Test Explorer in Visual Studio, or from the command prompt via dotnet test? This sounds like it might have been an issue with the IntelliSense information in Visual Studio rather than anything else - the namespaces are defined in the referenced projects. Did you try to build the Tests.Compiler.fsproj? In Visual Studio, in the Error List window you can also choose to list only the errors from the build or from IntelliSense to find out where the errors are reported.

**Comment by QuXing9** [comment]
Problem solved, thank you
