### ISSUE TITLE
Incorrect range information for diagnostics

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#1133]
The range information for the error messages is inaccurate for the following snippet:
![image](https://user-images.githubusercontent.com/34236215/132081280-2a2d3ffa-044e-4a39-8785-7812d3360874.png)

Extension version: 0.18.2108.160310

**Comment by samarsha** [comment]
So there are some extra diagnostics that are caused because `idxNegative` is typed as `InvalidType`, which the type checker complains about when it tries to check if it's a valid index type. It seems like the `InvalidType` gets a `Generated` range instead of `Inferred`. That is possibly a bug, but it should never matter because the compiler isn't supposed to generate additional type errors for `InvalidType` (the original error that caused an `InvalidType` should be enough).

PR #1150 removes these extra diagnostics. The remaining diagnostics look like they have correct ranges.
