### ISSUE TITLE
Operation containing the qubit array cannot be called twice.

### ISSUE THREAD

**Issue by QuXing9** [microsoft/qsharp-compiler#1253]
## TestCase

~~~c#
namespace Quantum.Kata.UnitaryPatterns {
	open Microsoft.Quantum.Intrinsic;
	open Microsoft.Quantum.Canon;

	operation StatePrep_DifferentBasis(qs:Qubit[], state:Int, alpha:Double) : Unit is Adj {
            ApplyToEachA(H, qs);
	}

	@EntryPoint()
	operation main() : Unit {
		use qs = Qubit[8];
		mutable state = 5;
		mutable alpha = -1.7163417363311559;
		mutable result = StatePrep_DifferentBasis(qs,state,alpha);
                use bs = Qubit[2];
		return StatePrep_DifferentBasis(bs, state, alpha);
	}
}
~~~

## Output
![image-20211111210300248](https://user-images.githubusercontent.com/40267809/141305011-349a6541-d013-4e5f-9052-112559dba58a.png)

## Environment

`dotnet version`: 3.1.414

`QDK version`: 0.20.2110171573

## Description

When I execute operation `StatePrep_DifferentBasis` the second time, it reports an error: `Unhandled exception:Released qubits are not in zero state.` Is this a normal behavior of QDK? Why is it happen?

**Comment by tcNickolas** [comment]
Yes, this is expected behavior when running programs on QDK simulators. You should get the same behavior even without the second array of qubits, by just allocating a qubit array, preparing a non-zero state on it, and releasing the qubits without returning them to the 0 state. 

Resetting the qubits to 0 state or measuring them before release is required by the Q# specification - not doing so may lead to computational errors, so, while this cannot be enforced on the compiler level, it is enforced by QDK simulators.

**Comment by QuXing9** [comment]
> Yes, this is expected behavior when running programs on QDK simulators. You should get the same behavior even without the second array of qubits, by just allocating a qubit array, preparing a non-zero state on it, and releasing the qubits without returning them to the 0 state
> 
> Resetting the qubits to 0 state or measuring them before release is required by the Q# specification - not doing so may lead to computational errors, so, while this cannot be enforced on the compiler level, it is enforced by QDK simulators.

Got it! Thank you!
