### ISSUE TITLE
Improve usability of the Q# formatter

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp-compiler#1289]
**Describe the solution you'd like**

* [x] Avoid overwriting files if there are no changes done to them.  
You can see this effect when the tool runs on files in format "UTF-8 with signature": the files get overwritten (in format without a signature) even if the tool doesn't update them otherwise. 
* [x] Offer a summary of the tool run upon its completion.
The tool quits without a summary, unless it exits with an error. Other msbuild-based tools, such as `dotnet build` and `dotnet test`, offer a summary of their run - whether the build succeeded, how many tests passed and failed, etc. It makes sense to say something like "X updates done in Y files" or "Y files processed, X updates done" to match that behavior.

**Describe alternatives you've considered**
I can see the changes done using `git diff`, and I can revert changes to the files if I see that there are no meaningful changes to them manually, but having this functionality in the tool itself would greatly improve its usability and ease of adoption.

**Comment by samarsha** [comment]
I think that not writing unchanged files and showing a summary of number of files changed sound reasonable.

> The tool quits without a summary, unless it exits with an error. Other msbuild-based tools, such as `dotnet build` and `dotnet test`, offer a summary of their run - whether the build succeeded, how many tests passed and failed, etc. It makes sense to say something like "X updates done in Y files" or "Y files processed, X updates done" to match that behavior.

I think it would make sense to compare the summary output of QsFmt with other formatters, rather than build or test commands. For example, `dotnet format` and `fantomas` outputs a line for each file updated (but doesn't tell you how many changes were made in the file). `cargo fmt` has no output at all.

A single file could have hundreds or thousands of individual formatting changes for every syntax tree node that needs whitespace changes. I am not sure how useful counting the number of these updates is compared to using a diff between the original and updated contents instead.

**Comment by tcNickolas** [comment]
I spent a bit more time with the Q# Formatter (https://github.com/microsoft/QuantumLibraries/pull/517), and to add based on that experience:
* Not overwriting unchanged files is very important for the user experience. All Q# libraries have a dependency on Standard, and it had a dozen files that were overwritten with a different encoding every time I ran the tool, that was rather inconvenient.
* Reporting the summary is mostly a convenience feature to distinguish "The tool failed" from "The tool succeeded". I don't think we need to report per-file status, maybe even just the number of files that were updated is sufficient?

**Comment by bettinaheim** [comment]
It looks like we are all in agreement on not overwriting unchanged files, and I believe that is in work. 

For the summary, what Scott suggests sounds reasonable and useful to me; it would be nice to track the number of updates made for the updating feature, but don't track (or at least don't print) that for the formatting changes. Personally, I would find it most useful if the updating feature could tell me which lines in which files were updated, so I could double check that (there is always Git diff, but some people might prefer to have that as part of the formatting output). @ScottCarda-MS Would that work with the implementation that you have?

**Comment by ScottCarda-MS** [comment]
@bettinaheim there's nothing in the formatter syntax tree that keeps track of location like that, so reporting back any kind of location information isn't reasonably doable at this time, unfortunately. It seems like there are a lot of different asks being surfaced regarding the summary. In order to move forward, I'd like to take a baby-steps approach with this. Let's get the overwriting prevention for unchanged files, and output what files were changed:
```
N files {formatted | updated }:
    File X { formatted | updated }.
    File Y { formatted | updated }.
    File Z { formatted | updated }.
```
(If Format and Update is used, there will be two consecutive blocks like this.)
I think this is the least invasive approach and we can get this out to users and see how they like that. If there is a need to iterate on it further, that can be addressed once we get some feedback.

**Comment by samarsha** [comment]
Thanks for the explanation, @tcNickolas - it sounds like the two main issues are not overwriting unchanged files, and a summary of number of files changed and/or a list of files changed (but not number of updates per file). I agree with @ScottCarda-MS that we can start with those and consider a more detailed summary later if it is still an issue.

**Comment by bettinaheim** [comment]
Sounds good to me.

**Comment by ScottCarda-MS** [comment]
Completed with #1341
