### ISSUE TITLE
Type checking should only rely on type inference when necessary

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#1345]
In a couple of places during expression verification, a type parameters is created even when concrete type information is available, and the available type information is captured as constraints collected in a first pass and used in a second pass to resolve these newly injected parameters. 

The implementation should not rely on type inference more than needed for the following reason: While type inference can and should be allowed to fail in some cases (e.g. type resolution is too expensive or ambiguous), it should never be acceptable to fail type checking for (valid usages of) types that are determined by the user code and don't require type inference in the first place. Put differently, for any type inference algorithm it should always be possible for a user to specify the type in case the inference fails - and the compiler should respect that type. The resolution logic should therefore only inject type parameters when it actually needs to, and not rely on inference for type information specified in the user code. 

Concretely, the current setup is also problematic when type constraints are not or cannot adequately be expressed because they depend on type information that has been (temporarily) removed in favor of relying on type inference. Consider the power operator:

```fsharp
    if lhs.ResolvedType.Resolution = BigInt then
        inference.Unify(ResolvedType.New Int, rhs.ResolvedType) |> List.iter diagnose
        lhs.ResolvedType
    else
        verifyArithmeticOp inference this.Range lhs rhs |> takeDiagnostics
```
all of these cases I believe should pass type checking:

```qsharp
    function AsBigInt (arg : Int, dummy : Unit) : BigInt {
        return 1L;
    }

    function Id<'T> (arg : 'T, dummy : Unit) : 'T {
        return arg;
    }

    function Foo () : BigInt {
        let a = AsBigInt(1, ());
        let res1 = a ^ 3;
        let b = Default<BigInt>();
        let res2 = b ^ 2;
        let getOne = AsBigInt(1, _);
        let c = getOne();
        let res3 = c ^ 3;
        let getOneGen = Id(1L, _);
        let d = getOneGen();
        let res4 = d ^ 2;
        let e = (Id(_, ())(1L));
        return e ^ 2;
    }
```

Additionally, there are similar cases around functor applications and callables where a known type is replaced by a type parameter.

**Comment by samarsha** [comment]
I think we should clarify a misconception about type inference: for languages like Q#, type checking *is* type inference. A Q# program is well-typed if and only if type inference succeeds without errors. I don't believe that it's possible to talk about type checking as a separate algorithm from type inference.

It sounds like what you are asking for is a separate, more limited type inference rule for call expressions that does not generate a fresh type variable in cases where the types of the callable and the arguments are fully known at the point where the call expression occurs. I would recommend against this approach, because the call expression inference rule is already very complicated by necessity, and adding an additional branching path will make it harder to reason about and provide another place for bugs to hide.

To accommodate conditional typing rules like what is needed for `^`, you can call `InferenceContext.Resolve` to resolve a type based on the information known at the current point of inference. This restores the original, non-HM behavior. For example, this patch fixes all cases in your example:

```diff
diff --git a/src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs b/src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs
index d151f357..4d6fbb8d 100644
--- a/src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs
+++ b/src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs
@@ -659,3 +659,3 @@ type QsExpression with
             let resolvedType =
-                if lhs.ResolvedType.Resolution = BigInt then
+                if inference.Resolve(lhs.ResolvedType).Resolution = BigInt then
                     inference.Unify(ResolvedType.New Int, rhs.ResolvedType) |> List.iter diagnose
```

> Additionally, there are similar cases around functor applications and callables where a known type is replaced by a type parameter.

Could you provide examples of this?
