### ISSUE TITLE
Clarify the Precedence of the Lambda Operator

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp-compiler#1358]
The precedence of the lambda operator should be specified properly in the compiler code.
See [here](https://github.com/microsoft/qsharp-compiler/pull/1307#discussion_r794781466).

**Comment by bettinaheim** [comment]
As part of writing the specs I believe it is most reasonable to just add a sentence about lambdas under the combinator section for reference indicating that all operators, modifiers and combinators bind stronger. I think it is most reasonable to not list the lambda arrow as operator since the lhs is a symbol tuple and it thus doesn't really fit the operator description. I'd hence suggest to not list it as an operator, though I will mention it in the spec since it is relevant for understanding operator expressions.

**Comment by bettinaheim** [comment]
I updated the Q# code output: https://github.com/microsoft/qsharp-compiler/pull/1360.
