### ISSUE TITLE
Code Completion for files that are not associated with a compilation unit

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp-compiler#304]
**Describe the bug**

Code Completion in Visual Studio for qs files will not recognize operations in included namespaces like the Intrinsic namespace. This is with editing a qs file that is not part of a project.

**To Reproduce**

Create a qs file and open the file in Visual Studio. The file should not be in a project. Begin a namespace and open Microsoft.Quantum.Intrinsic namespace. Begin an operation. In the operation try to type 'X' for the X operation.

Auto-complete will suggest PauliX rather than the X operation, and ignoring the suggestions and typing '(' to begin the argument list for the X operation will result in the suggestion for the PauliX replacing the intended operation X call.

**Expected behavior**

The X operation should be suggested because the opened namespace should be compiled ahead of time. Or the suggestions should not appear for a qs file not in a project. Or the suggestions should not automatically replace what you are typing.

**Comment by bettinaheim** [comment]
@ScottCarda-MS If a souce file cannot be associated with a compilation unit (project), then almost all of the language server functionality is disabled (we can't give semantic information without knowing the context in which to interprete a file). I don't know what you were looking for here; implementing code completion that e.g. works like the completion for text files (complete everything that has been used previously) seems like a fair amount of work compared to the benefits/use cases.

**Comment by bettinaheim** [comment]
I double checked the behavior of F# and C# in this case. It looks like both make a fair amount of effort to be clever in this case (they give intellisense for things defined in that file as well as even for some well-known things, with accurate context interpretation within the limits of what is possible). Given the length of our todo list, this still seems like a more advance feature to consider implementing a bit later down the line. I'd hence like to defer this, but it also would be a cool thing to pick up if someone feels up to the challenge of doing this as a spare time project (I'm happy to advice).

**Comment by samarsha** [comment]
@bettinaheim I believe the issue you're referring to is resolved by #560. The original bug report, here, though, was about Visual Studio automatically accepting completion items when `(` is pressed, even if the currently selected completion item doesn't match what the user intended. This can happen if the Q# file is not part of a project, but also if you want to type in a currently undefined identifier that you will define later.

Since this is Visual Studio behavior (that doesn't happen in Visual Studio Code), it's possible that there's nothing we can do, but it might be worth investigating if there's a workaround.

**Comment by bettinaheim** [comment]
Closing as addressed with #560.
