### ISSUE TITLE
Provide additional help when unknown identifier caused by missing open statement

### ISSUE THREAD

**Issue by cgranade** [microsoft/qsharp-compiler#42]
**Is your feature request related to a problem? Please describe.**
When compiling Q# (either as a part of a project, or through IQ#), if an unknown identifier error is caused by forgetting an open statement, it would be great if that could be hinted at in the error message itself. This information is already available through code actions, but that may not be obvious when refactoring a larger project; moreover, code actions aren't available through Jupyter clients. 

**Describe the solution you'd like**
At the moment, error messages look a bit like the following:
```
/snippet:(3,16): error QS5022: No identifier with that name exists.
```
An improvement might be something more similar to:
```
/snippet:(3,16): error QS5022: No identifier with the name MResetZ exists.
    You may be able to fix this error by adding:
    open Microsoft.Quantum.Measurement;
```

**Additional context**
This error currently comes up a lot in IQ# especially due to microsoft/iqsharp#15.

**Comment by tcNickolas** [comment]
It would also be useful to just mention the non-existing name instead of referring to it as "that name"; for Q# projects we can see IntelliSense underlining the name or double-click on the error message to navigate to it, but in Jupyter Notebooks there are only line/character numbers which are rather inconvenient.

**Comment by cgranade** [comment]
That's a good point, @tcNickolas, totally agreed. I've modified the desired solution in my feature request accordingly.

**Comment by bettinaheim** [comment]
Thanks, both for filing! 
I tagged it as a bug, since this is a quick and easy thing for anybody to pick up without requiring further discussions on how to best do this. The corresponding infrastructure is already there, since that exact information is used for code actions on unknown identifiers. 
For anyone picking this up, I can give more precise info if desired.

**Comment by bettinaheim** [comment]
Addressed with PR https://github.com/microsoft/qsharp-compiler/pull/235.

**Comment by mridulsar** [comment]
It looks like I am still running into the same error message as mentioned above by @cgranade. 
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "Measure" exists.
