### ISSUE TITLE
Official Q# syntax file not recognized by GitHub's Linguist

### ISSUE THREAD

**Issue by JakuJ** [microsoft/qsharp-compiler#504]
**Is your feature request related to a problem? Please describe.**
I'm working on adding Q# support to GitHub's Linguist. In order to add syntax highlighting I need to provide an up-to-date syntax file for the language. I am aware of the one [in the VSCode extension directory](https://github.com/microsoft/qsharp-compiler/blob/master/src/VSCodeExtension/syntaxes/qsharp.tmLanguage.json.v.template), however, it's not recognized by the utility that Linguist uses to scrape syntax files from repositories. The issue is that the extension it uses is not valid, and thus the tool cannot find it.

**Describe the solution you'd like**
I'd like the syntax file in the repository to use one of the extensions that Linguist can recognize, for instance ".tmLanguage" or ".json" (see [this function](https://github.com/github/linguist/blob/b24ff11d9cf60dd996156a718f83024c9436e5ea/tools/grammars/compiler/loader.go#L106) for reference).

**Describe alternatives you've considered**
- Using another repository as a source for the syntax file - I've found [one](https://github.com/ivangabriele/qsharp-tmLanguage), but it's outdated. For instance, the "internal" keyword is still illegal in this one. I'd rather have the syntax come from the official repository for the language.
- Changing the way Linguist scans repositories for syntax files - it probably makes more sense for the language to adapt to GitHub's standards and not the other way around.

**Additional context**
I've submitted a pull request (github/linguist#4901) to Linguist to add Q# as a recognized language. The syntax is not strictly necessary at the time of adding a language, but it'd be nice to have GitHub highlight Q# source files from day one.

I've seen a reference to `syntaxes/qsharp.tmLanguage.json` in the `.gitignore`, so I guess the file is generated locally after installing the extension. However, the .template file is a valid syntax file as well ([link to Lightshow](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fqsharp-compiler%2Fblob%2Fmaster%2Fsrc%2FVSCodeExtension%2Fsyntaxes%2Fqsharp.tmLanguage.json.v.template&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fmicrosoft%2FQuantum%2Fmaster%2Fsamples%2Fnumerics%2FCustomModAdd%2FCustomModAdd.qs&code=)), so just changing the extension to one that's recognized by Linguist would most likely be enough.

**Comment by samarsha** [comment]
Thanks for looking into this, adding Q# to the GitHub languages would be really cool!

The reason for the `.v.template` extension is because the version number for the grammar is a template variable that is filled in at build time by the `bootstrap.ps1` script, which looks for all files that end in `.v.template`.

```
"version": "#SEMVER_VERSION#",
```

So changing the extension would mean we'd need to change how the template script processes it. I'm not sure what the best solution is that would avoid hard-coding a version number. Maybe we can store the grammar without a version number in a separate file that has the correct extension, and only add the version number when it's packaged in the VS Code extension. (Or maybe we could get rid of the version number from the file, so it doesn't need to be processed as a template - I'm not sure if the version number is necessary if the VS Code extension itself also has a version number.)

I'll look into this, let me know if you have suggestions about the version number variable problem though!
