### ISSUE TITLE
Downgrade entry point in library error to warning

### ISSUE THREAD

**Issue by rmshaffer** [microsoft/qsharp-compiler#571]
**Is your feature request related to a problem? Please describe.**
After discussion with @bettinaheim, we believe that the issue https://github.com/microsoft/iqsharp/issues/266 is due to the fact that IQ# is discarding certain compiler errors and attempting to build an assembly anyway, but the compiler is not executing the rewrite steps after the error has occurred.

**Describe the solution you'd like**
We would like a new option in `CompilationLoader.Configuration` by which we can tell the compiler to execute the rewrite steps anyway, even if there were errors in compilation.

Here is the code in IQ# where this new option would be consumed:
https://github.com/microsoft/iqsharp/blob/186bacb0570ef8688ffa8dac48d6a1230169b61f/src/Core/Compiler/CompilerService.cs#L129-L138

**Describe alternatives you've considered**
There are other options for IQ# to work around the particular compiler errors that are being discarded, but simply compiling and then discarding the errors is the approach that requires the least low-level code manipulation on the IQ# side, and which has been working fine for the last couple of months.

**Comment by ScottCarda-MS** [comment]
I don't think it is a good precedent to set to allow the compiler to create a compilation despite errors having been thrown. This leaves the compiler open to having to support use cases for the compiler in which erroneous compilations occurred, which is not a situation we want to be in. It also biases future development work on the compiler to not have as strict a standard when considering what should and shouldn't be errors in the future, if users are capable of ignoring the error anyway. I'm concerned that this is a bad "easy" solution to the problem at hand with the IQ#, and that we should use this opportunity to come up with a better solution.

**Comment by samarsha** [comment]
The reason that rewrite steps don't execute when there are errors is because they assume that the syntax tree they are given is valid; for example C# generation was crashing with an exception when it encountered invalid identifiers, causing confusing error messages.

I think if we are considering this we need to make it clear that rewrite steps can receive invalid ASTs, and make sure all of our built-in rewrite steps can handle any syntax tree gracefully (maybe with a precondition to skip the rewrite step if the AST is invalid).

But mostly I agree with @ScottCarda-MS. In general, errors are not supposed to be optional. Wouldn't it be better to make this particular error about entry points in libraries into a warning?

**Comment by rmshaffer** [comment]
I agree, that also sounds like a reasonable solution and doesn’t set a bad precedent about ignoring errors. Feel free to repurpose this issue for that if you feel that’s the best way to address this.

**Comment by rmshaffer** [comment]
@samarsha @ScottCarda-MS Do you think there would be any issues with making the change to downgrade "entry point in library" to a warning? Would it be reasonable for me to raise a PR for that?

**Comment by bettinaheim** [comment]
@rmshaffer, @samarsha, @ScottCarda-MS Rewrite steps indeed should only deal with valid compilations. Making it a warning instead of an error I think is a good solution in this case. I'll update the title accordingly, and we can possibly take a look at that for October.
