### ISSUE TITLE
Preserve API documentation on deprecated operations

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp-compiler#592]
**Is your feature request related to a problem? Please describe.**
Currently we remove the API documentation as soon as we mark the operation deprecated, so its page in the docs only says "use the new operation instead". A person who sees the deprecation notice and wants to switch the code to use the new operation might not remember exactly the details of what the old operation did, and it's fairly hard to dig them out at this point, especially if the new operation has different set of parameters. 

For example, [DrawRandomInt](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.random.drawrandomint) replaces [RandomIntPow2](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math.randomintpow2) but requires figuring out the range of numbers generated.

**Describe the solution you'd like**
It would be nice to keep API documentation for deprecated operations/functions/UDTs until they are removed completely. 

**Describe alternatives you've considered**
One can figure out the necessary parameters by diving into the libraries source code (in this example getting to the [source file with RandomIntPow2 definition](https://github.com/microsoft/QuantumLibraries/blob/26ae8b963f7f92d46c818b49c28105a22cac5be7/Standard/src/Math/Random.qs#L10) will allow to figure out the necessary parameters), but going to the libraries code requires fairly in-depth familiarity with our repos, which I'm afraid not all Q# users have.

**Comment by samarsha** [comment]
The compiler replaces the *short* summary with the deprecation message, but preserves the *long* summary (adding the deprecation message to the end, instead of replacing it). I am not sure which summary is used on the docs pages (I would guess long summary, but I'm not sure).

Confusingly, the short summary is saved to to the individual callable/type YAML file, while the long summary is saved to the namespace YAML file, which seems backwards to me. That might mean the docs page is rendering the wrong summary.

This is complicated by the libraries removing the doc comment from the source code for deprecated items, which means I can't find an example of a deprecated item with its original doc comment in source code to see how it's rendered on the docs page.

@cgranade Do you know what the docs page renders if the original doc comment is kept in the source code?

**Comment by cgranade** [comment]
> The compiler replaces the _short_ summary with the deprecation message, but preserves the _long_ summary (adding the deprecation message to the end, instead of replacing it). I am not sure which summary is used on the docs pages (I would guess long summary, but I'm not sure).
> 
> Confusingly, the short summary is saved to to the individual callable/type YAML file, while the long summary is saved to the namespace YAML file, which seems backwards to me. That might mean the docs page is rendering the wrong summary.

There's a lot of confusion around the Q# → YAML → HTML pipeline, most of which stems from that the YAML format is based on Q# 0.1 (e.g.: that only had summaries and not long descriptions). Agreed, though, we should check if the docs page has mixed something up there.

> This is complicated by the libraries removing the doc comment from the source code for deprecated items, which means I can't find an example of a deprecated item with its original doc comment in source code to see how it's rendered on the docs page.
> 
> @cgranade Do you know what the docs page renders if the original doc comment is kept in the source code?

We can create a branch to test that, restoring some old comments from Git history to try and confirm. The API documentation pipeline when run from the e2e build should create a docs branch we can use to look at that.

**Comment by samarsha** [comment]
I created PR #605 that changes the YAML output to make more sense to me, but we should test it with the built documentation to make sure.
