### ISSUE TITLE
Q# code actions in Visual Studio extension lead to UI unresponsiveness

### ISSUE THREAD

**Issue by ricardo-espinoza** [microsoft/qsharp-compiler#829]
**Describe the bug**

In QDK version 0.14.2011120240, the Visual Studio extension for Q# is failing to respond correctly to invocation of code actions on .qs files. This appears to be caused by the language server not responding to those requests, but more investigation is required.

**To Reproduce**

1. Open a Q# project in Visual Studio
2. Select a portion of the code, and invoke a quick action (e.g. "Add documentation for...")
3. Wait for the VS application to freeze.

**System information**

- Extension version 0.14.2011.120240
- Visual Studio 16.8.4

**Comment by bettinaheim** [comment]
@ricardo-espinoza There has been no change in the server or compile that I think in any way could have impacted how the server behaves, and the server is the same and working fine for VS Code. My recommendation is to check whether there was version update in the VS client that required a change to adjust, and then enable and check the logging of messages going back and forth. You may have to reach out to the VS team, since this may not be on our end.
