### ISSUE TITLE
Package formatter as a .NET tool

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#864]
To make it easier to install and use, the formatter should be packaged as a .NET tool that can be used with the `dotnet tool` command.

**Comment by ScottCarda-MS** [comment]
Since this issue was opened, the development of the formatter has gone in a different direction. Rather than packaging the formatter as a .NET tool, the formatter is packaged with the rest of the QDK and is integrated into the Q# IDE extensions. Packaging the formatter as a .NET tool would require some major refactoring to the product. There are no plans at this time to package the formatter as a .NET tool.
