### ISSUE TITLE
QIR generation fails for callables that require conditional rewrite

### ISSUE THREAD

**Issue by irinayat-MS** [microsoft/qsharp-compiler#876]
The following Q# code compiles without errors if either `<QirGeneration>True</QirGeneration>` or `<ExecutionTarget>honeywell.qpu</ExecutionTarget>` is not set.
```
    operation NoArgs() : Unit
    is Adj+Ctl {
        body (...) {
            use q = Qubit();
            X(q);
            if M(q) != One { fail("Unexpected qubit state"); }
        }
        adjoint self;
        controlled (ctrls, ...) {
            use q = Qubit();
            Controlled X(ctrls, q);
            if M(q) != One { fail("Unexpected qubit state"); }
        }
    }

    operation TestFunctorsNoArgs() : Unit {
        NoArgs();
    }
```
And fails with error: "microsoft.quantum.sdk\0.15.2102128704-alpha\Sdk\Sdk.targets(148,5): error : Q# compiler failed with exit code: -13." otherwise.

**Comment by bettinaheim** [comment]
I've look at issue and the root of it is that the Classical Control transformation creates TupleValues that have only one item while the expression validation upon creating TypedExpressions ensures that the expression kind matches the type (and a tuple with a single item does not exist at as a type). We need to either enforce that ValueTuples cannot have a single item in the typed checked data structures (which is a bit painful since we are using the same data structure for the unchecked syntax noted generated by parsing), or we need to adjust the generation to strip the tuple wrapping for tuples that have a single item.

**Comment by bettinaheim** [comment]
Fixed with #906.

**Comment by samarsha** [comment]
> We need to either enforce that ValueTuples cannot have a single item in the typed checked data structures (which is a bit painful since we are using the same data structure for the unchecked syntax nodes generated by parsing)

What about normalizing tuples at parse time? Then we could change `QsExpressionKind.ValueTuple` to have a type that required at least two elements.

**Comment by samarsha** [comment]
> > We need to either enforce that ValueTuples cannot have a single item in the typed checked data structures (which is a bit painful since we are using the same data structure for the unchecked syntax nodes generated by parsing)
> 
> What about normalizing tuples at parse time? Then we could change `QsExpressionKind.ValueTuple` to have a type that required at least two elements.

@bettinaheim thoughts?
