### ISSUE TITLE
NU5037 error when creating new Q# project.

### ISSUE THREAD

**Issue by Majd223** [microsoft/qsharp-compiler#966]
**Describe the bug**

Using the Q# extension in VS code to create a new Q# project, a lot of errors appear making it unable to use QDK...
**To Reproduce**

1. Go to 'View'
2. Click on 'Command Palette...'
3. Click on 'Q#: Create new Project... '
4. Select where you want the project files to be and name the project.
5. Go to the Q# you just created and you will start seeing the errors on all the Q# syntax.

**Expected behavior**

Q# already creates some code to start with (The operation SayHello() that have the Message "Hello quantum world!")
usually you should be able to run it with dotnet run and get the message Hello quantum world.
When I do dotnet run (or dotnet build), I get the following error:

```
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error NU5037: The package is missing the required nuspec file. Path: C:\Users\Majd\.nuget\packages\libllvm.runtime.win-x64\11.0.0 [C:\Users\Majd\testq\testq.csproj]

The build failed. Fix the build errors and run again.
```

**Screenshots**

Here is a screenshot of what I get:
![Screenshot_4](https://user-images.githubusercontent.com/76471403/114479923-4fcb2a80-9bb6-11eb-88d3-c3c78c767470.png)

**System information**

- Version of the NuGet package or extension for which the problem occurs
.csproj file:
```
<Project Sdk="Microsoft.Quantum.Sdk/0.15.2103133969">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```
- Your operating system and .NET Core version:
![Screenshot_6](https://user-images.githubusercontent.com/76471403/114480767-0da2e880-9bb8-11eb-919e-0eea9540323e.png)

- For issues with extensions, the version of the IDE for which the problem occurs 
VS code Info:
![Screenshot_7](https://user-images.githubusercontent.com/76471403/114480976-71c5ac80-9bb8-11eb-8760-528e1f3645e4.png)
Using the following extension: 
![Screenshot_8](https://user-images.githubusercontent.com/76471403/114481203-f31d3f00-9bb8-11eb-9a92-04a9d35346e9.png)

**Additional context**
Notice that when I roll back to QDK 0.15.2102129448 this problem is solved.

**Comment by bettinaheim** [comment]
@Majd223 Thanks for letting us know!
I have not seen or been able to reproduce the issue locally; I believe this may be an issue with packages not having been properly restored. Could you please run `dotnet restore projectfile.csproj` replacing the project file name as needed? Depending on the download speed, the command may take a while - our apologies; the llvm libraries are somewhat big, and we are working on removing that dependency as much as possible in a future release. The restore may also have failed due to a connection issue while downloading and resulted in the broken state that may have lead to the error encountered here. Please double check that the restore terminates successfully before building.

**Comment by Majd223** [comment]
Thank you for your reply @bettinaheim.
when I do as you said replacing projectfile.csproj with my project name I get the same NU5037 error.

**Comment by bettinaheim** [comment]
@Majd223 I think that points to a corrupt package/state. Could you try first to delete both the bin and the obj folder for the project before running the restore again? 
If that doesn't work, then could you either run `nuget locals -clear all` (this is the reliable, but somewhat invasive way, since it requires to re-download all packages that you are using), or delete all nuget packages that have llvm in their name from your .nuget folder (on Windows that folder is under C:\Users\yourusername\.nuget\packages). Running the restore again should hopefully work after that.

**Comment by Majd223** [comment]
@bettinaheim  I tried deleting obj and bin then doing the restore command -> didn't work
Deleting all files with llvm in their name -> didn't work
after deleting both obj and bin the restore command runs into the error and the files don't get restored. I tried creating a new project and try again deleting the llvm files then doing the build with and without bin and obj but still no luck. Sorry this is happening.

**Comment by Majd223** [comment]
Forgot to mention when I run `nuget locals -clear all` I get:
```
'nuget' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bettinaheim** [comment]
@Majd223 Sorry for the hassle! I am somewhat confused by this. If you type `dotnet nuget --version`, what version do you have? You can also use `dotnet nuget locals --clear all` instead to clear out the cache.

**Comment by Majd223** [comment]
@bettinaheim 
my Nuget version:
```
NuGet Command Line
5.9.0.7122
```
dotnet nuget locals --clear all WORKED THANK YOU!!!

**Comment by bettinaheim** [comment]
@Majd223 Great! Worked as in you can now build the project successfully?

**Comment by Majd223** [comment]
@bettinaheim Yes I can build with no errors. also tried it on my old projects that had the problem and created a new project to test it out. Looks like it solved my problem. Thank you again.

**Comment by bettinaheim** [comment]
No problem - thanks for trying it out and giving us the feedback!
